/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <iostream>
#include <cstdint>
using namespace std;

int main(){
	uint32_t prev1 = 1;
	uint32_t prev2 = 1;
	uint64_t sum = 0;
	for (uint32_t i = 2; i <= 4000000; i = prev1 + prev2){
		if(i % 2 == 0) sum += i;
		prev2 = prev1;
		prev1 = i;
	}
	cout << sum << '\n';
}
